language: java

jdk:
  - oraclejdk8

sudo: false  # as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

script: mvn clean install

cache:
  directories:
    - $HOME/.m2

after_success:


after_failure: